### ISSUE TITLE
Display “Illegal instruction (core dumped)” when running

### ISSUE THREAD

**Issue by zjw964** [accelerated-graph-mining/hash-join-mce#1]
Hi,

I building the code with GCC7 and TBB, and ran on Intel(R) Xeon(R) CPU,but it report an error with "Illegal instruction (core dumped)"， what is the reason and how to solve it?
![image](https://user-images.githubusercontent.com/71832116/105155208-472dff80-5b45-11eb-9639-c103152f8940.png)

Looking forward to your reply.
Great work by the way.

Cheers,

**Comment by jovan-blanusa** [comment]
Hi, 

Does your CPU has the support for AVX512? Could you copy the output of _lscpu_ command?

Best
